service: user-crud-sls-app

provider:
  name: aws
  profile: juan
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
      seed: true
    seed: 
      users:
        sources:
          table: user-crud-sls-app
          sources: [./users_seed.json]     
    migration:
      dir: offline/migrations



functions:
  get:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: GET

	
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-crud-sls-app
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1